### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by kkalisz** [itsJoKr/FragmentArgs#2]
Hi, 
library is not working as intended, after rotation arguments are not recreated.

There is no diffrence in use this library or write own setter in fragment. Both methods will not work with recretation of fragment. 

Passing arguments with bundle is only 100% reliable way. It will properly handle fragment recreation and trimmimg memory.

**Comment by itsJoKr** [comment]
Hi,
I made this for fun and this library shouldn't be used in real projects as I wrote on reddit, but some people shared it on some other websites.

Yea, this library doesn't care about saving state and recreation. You should use bundle, unless you are really lazy then you can use this library i found in the meantime (that solves same problem and even has same name) but actually works: https://github.com/sockeqwe/fragmentargs
